### ISSUE TITLE
Question about the training dataset scalability

### ISSUE THREAD

**Issue by memoiry** [SMSD75/Timetuning#3]
Hi,

The paper uses YTVOS as training dataset, which however only consist of ~3-4k training videos. I'm wondering have you tried to use larger dataset like K400 as training dataset, which consist of 200k videos to verify the scalability of the proposed methods.

Thanks!

**Comment by SMSD75** [comment]
Hi, 

Scalability here is slightly different compared to classification tasks. Because we can add to the number of objects in a training set or the number of training examples. We observed that training on MOS produces better results, likely due to the extra number of objects. For Kinetics, we didn't see any significant improvement, but still, it is hard to measure; since we tested on Image datasets and the distribution shift itself adds some noise to the real effect of important factors.
